export default function(){
    return[
        {
            id: 1,
            title: 'Astérix et Obélix : Mission Cléopâtre',
            genre: ['Comedy'],
            release_date: 2002,
            director: 'Alain Chabat',
            actors: 'Christian Clavier, Gérard Depardieu, Jamel Debouze',
            cover: 'http://fr.web.img3.acsta.net/medias/nmedia/00/02/39/29/aff_asterix.jpg',
            upload_date: 20160512,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 2,
            title: 'Donnie Darko',
            genre: ['Science Fiction'],
            release_date: 2001,
            director: 'Richard Kelly',
            actors: 'Jake Gyllenhaal,Jena Malone',
            cover: 'http://t3.gstatic.com/images?q=tbn:ANd9GcRC5hipJcegri7fW1U29L4LnJgeJzjHQWlBABqo1QpvUHEBeOTp',
            upload_date: 20161201,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 3,
            title: 'Lord Of The Rings: The Return Of The King',
            genre: ['Action', 'Fantasy'],
            release_date: 2003,
            director: 'Peter Jackson',
            actors: 'Elijah Wood, Orlando Bloom, Viggo Mortensen, Ian Mckellen',
            cover: 'http://fr.web.img4.acsta.net/c_215_290/medias/nmedia/18/35/14/33/18366630.jpg',
            upload_date: 20151021,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 4,
            title: 'Shining',
            genre: ['Horror'],
            release_date: 1980,
            director: 'Stanley Kubrick',
            actors: 'Jack Nicholson, Shelley Duvall',
            cover: 'http://t1.gstatic.com/images?q=tbn:ANd9GcTyub5mS3wPMSXcUYccXgIDN480wL2RuEnjmGKmjwwhJrRGeNOP',
            upload_date: 20091216,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 5,
            title: 'Warcraft',
            genre: ['Action','Fantasy'],
            release_date: 2016,
            director: 'Duncan Jones',
            actors: 'Travis Fimmel, Paula Patton, Toby Kebbell',
            cover: 'http://t2.gstatic.com/images?q=tbn:ANd9GcSs5pZVpKQoFEyViSUPImy1EuPPPWQ37bO5FeeKyaINmzUHE9ht',
            upload_date: 20170123,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 6,
            title: 'Ocean Eleven',
            genre: ['Other'],
            release_date: 2001,
            director: 'Steven Soderbergh',
            actors: 'George Clooney, Brad Pitt, Matt Damon',
            cover: 'http://www.gstatic.com/tv/thumb/movieposters/28801/p28801_p_v8_aa.jpg',
            upload_date: 20090205,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 7,
            title: 'Gran Torino',
            genre: ['Drama'],
            release_date: 2009,
            director: 'Clint Eastwood',
            actors: 'Clint Eastwood, Bee Vang',
            cover: 'http://fr.web.img6.acsta.net/medias/nmedia/18/67/90/93/19057560.jpg',
            upload_date: 20160519,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 8,
            title: 'The Visit',
            genre: ['Horror'],
            release_date: 2015,
            director: 'M. Night Shyamalan',
            actors: 'Olivia DeJonge, Ed Oxenbould, Deanna Dunagan, Peter McRobbie',
            cover: 'http://t2.gstatic.com/images?q=tbn:ANd9GcSsxiIWO-MqVTjurupFqL78jbAbeyD5PY5LPtJeeW0aZl2e95uT',
            upload_date: 20160718,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 9,
            title: 'Matrix',
            genre: ['Action', 'Science Fiction'],
            release_date: 1999,
            director: 'Lana Wachowski, Andy Wachowski',
            actors: 'Keanu Reeves,Laurence Fishburne',
            cover: 'http://pays.imaginaire.free.fr/Images%20Films/Matrix/Film/Film%20Matrix%20Titre.jpg',
            upload_date: 20130815,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 10,
            title: 'Harry Potter And The Deathly Hollows: Part I',
            genre: ['Action,Fantasy'],
            release_date: 2010,
            director: 'David Yates',
            actors: 'Daniel Radcliffe, Rupert Grint, Emma Watson',
            cover: 'http://fr.web.img5.acsta.net/medias/nmedia/18/69/69/81/19590744.jpg',
            upload_date: 20130203,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 11,
            title: 'Bienvenue chez les Chtis',
            genre: ['Comedy'],
            release_date: 2008,
            director: 'Dany Boon',
            actors: 'Dany Boon, Kad Merad',
            cover: 'http://fr.web.img5.acsta.net/medias/nmedia/18/64/74/53/18889951.jpg',
            upload_date: 20151130,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 12,
            title: 'The Dark Knight',
            genre: ['Action'],
            release_date: 2008,
            director: 'Christopher Nolan',
            actors: 'Christian Bale, Heath Ledger',
            cover: 'http://fr.web.img2.acsta.net/medias/nmedia/18/63/97/89/18949761.jpg',
            upload_date: 20160229,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 13,
            title: 'Captain Fantastic',
            genre: ['Drama'],
            release_date: 2016,
            director: 'Matt Ross',
            actors: 'Viggo Mortensen, George MacKay',
            cover: 'http://t3.gstatic.com/images?q=tbn:ANd9GcQ6YFpWi6v8WvU3MCP0NE9aSDmPs1aJG-HwusLIf-n0IEAhFCYo',
            upload_date: 20161225,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 14,
            title: 'L\' Exorciste',
            genre: ['Horror'],
            release_date: 1974,
            director: 'William Friedkin',
            actors: 'Linda Blair, Ellen Burstyn, Jason Miller',
            cover: 'http://fr.web.img5.acsta.net/medias/nmedia/18/65/19/82/18835952.jpg',
            upload_date: 20080911,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 15,
            title: 'Inglorious Basterds',
            genre: ['Action'],
            release_date: 2009,
            director: 'Quentin Tarantino, Eli Roth',
            actors: 'Christoph Waltz, Brad Pitt, Melanie Laurent',
            cover: 'http://fr.web.img2.acsta.net/medias/nmedia/18/70/45/22/19123474.jpg',
            upload_date: 20130711,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 16,
            title: 'Narnia',
            genre: ['Fantasy'],
            release_date: 2005,
            director: 'Andrew Adamson',
            actors: 'Georgie Henley, Skandar Keynes, William Moseley, Anna Popplewell',
            cover: 'http://fr.web.img4.acsta.net/medias/nmedia/18/35/53/32/18434204.jpg',
            upload_date: 20081128,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 17,
            title: 'Midnight Special',
            genre: ['Science Fiction'],
            release_date: 2016,
            director: 'Jeff Nichols',
            actors: 'Michael Shannon, Kirsten Dunst, Adam Driver, Jaeden Lieberher',
            cover: 'http://t0.gstatic.com/images?q=tbn:ANd9GcRry9GXrxI9hmk4Xe0y9fWk7tPBOEg9lMB_ncqdF5TP2jTw5xYG',
            upload_date: 20170124,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        },
        {
            id: 18,
            title: 'American History X',
            genre: ['Drama'],
            release_date: 1998,
            director: 'Tony Kaye',
            actors: 'Edward Norton, Edward Furlong',
            cover: 'http://www.gstatic.com/tv/thumb/movieposters/21980/p21980_p_v8_ae.jpg',
            upload_date: 20161010,
            uploader: 'admin',
            synopsis:'Lorem ipsum...'
        }
    ]

}